---

- hosts: 10.101.1.108
  become: true
  tasks:


  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install the apache 2 package
    apt:
      name: apache2

  - name: add php suppport for apache
    apt:
      name: libapache2-mod-php

