- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID67F5FrrCxzIqDDM5HH9zBHsAg0u2JMaGN8mUHb43nz ansible"

- name: Generate sshd_config file from ssh_template_file
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
  